version: '3'

services:
  app:
    build: .
    entrypoint: sh ./.docker/entrypoint.sh
    container_name: api-gerenciador
    ports:
      - 3001:3001
    volumes:
      - .:/home/app/nest_project
    tty: true
    networks:
      - app-gerenciador-funcionarios

  db:
    image: mongo:4.4
    container_name: db
    ports:
      - 27017:27017
    volumes:
      - /mongodb/dbdata:/data/db
      - /mongodb/configdb:/data/configdb
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: user-database
    networks:
      - app-gerenciador-funcionarios

networks:
  app-gerenciador-funcionarios:
    driver: bridge
